services:
  dataset_manager:
    build:
      context: .
      dockerfile: dataset_manager/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  neural_net:
    build:
      context: .
      dockerfile: neural_net/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge